# Generated by Django 4.2.7 on 2023-11-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hikmahcart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailtransaksi',
            options={'verbose_name_plural': 'Data Detail Transaksi'},
        ),
        migrations.AlterModelOptions(
            name='transaksi',
            options={'verbose_name_plural': 'Data Transaksi'},
        ),
    ]
